# Generated by Django 4.1.2 on 2022-11-30 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangocrud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(blank=True, to='djangocrud.categories')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rlibrary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
